version: 3

tasks:
  cloud-init-unit-conf:
    internal: true
    label: '{{.TASK}}:{{.FILE_CNT}}'
    requires:
      vars: [USER_DATA, FILE_PATH, FILE_CNT]
    env:
      WRITE_FILE_PATH: '{{.FILE_PATH}}'
      WRITE_FILE_CNT: '{{.FILE_CNT}}'
    cmds:
      - yq -i --from-file=cloud-init.yq {{.USER_DATA}}

  cloud-init-unit:
    internal: true
    requires:
      vars: [UNIT, USER_DATA]
    dir: '{{.UNIT}}'
    vars:
      UNIT_DIR: /lib/systemd/system/{{.UNIT}}.d
      CONF_FILES:
        sh: find {{.UNIT}} -maxdepth 1 -type f -name '*.conf' -printf '%f\n'
    cmds:
      - for: {var: CONF_FILES}
        task: cloud-init-unit-conf
        vars:
          FILE_PATH: '{{.UNIT_DIR}}/{{.ITEM}}'
          FILE_CNT: '{{.UNIT}}/{{.ITEM}}'
          USER_DATA: '{{.USER_DATA}}'

  cloud-init:
    desc: cloud-init configuration
    requires:
      vars: [USER_DATA]
    vars:
      SYSTEMD_UNITS:
        sh: find -maxdepth 1 -type d -name '*.service' -printf '%f\n'
    cmds:
      - for: {var: SYSTEMD_UNITS}
        task: cloud-init-unit
        vars:
          UNIT: '{{.ITEM}}'
          USER_DATA: '{{.USER_DATA}}'

  reload-units:
    internal: true
    status:
      - test -n "{{.MNT_POINT}}"
    cmds:
      - systemctl daemon-reload

  restart-unit:
    internal: true
    requires:
      vars: [UNIT]
    cmds:
      - systemctl --no-block try-restart {{.UNIT}}

  restart-units:
    internal: true
    vars:
      SYSTEMD_UNITS:
        sh: find -maxdepth 1 -type d -name '*.service' -printf '%f\n'
    cmds:
      - for: {var: SYSTEMD_UNITS}
        task: restart-unit
        vars:
          UNIT: '{{.ITEM}}'

  systemd-units:
    desc: Tune systemd units (services)
    aliases: [default]
    status:
      - test -n "{{.MNT_POINT}}"
    cmds:
      - task: reload-units
      - task: restart-units
