version: 2
ethernets:
    eth:
        match:
            name: eth*
        dhcp4: false
        optional: true
    enx:
        match:
            name: enx*
        dhcp4: false
        optional: true

bridges:
    br-lan:
        critical: true
        dhcp4: true
        link-local: []
        accept-ra: false
        interfaces:
        - eth
        - enx

