#cloud-config

hostname: freepx

chpasswd:
  expire: true
  users:
    - name: ubuntu
      password: ubuntu
      type: text

ssh_pwauth: true

package_update: true
package_upgrade: false
package_reboot_if_required: false

apt:
  sources:
    nodesource:
      source: |
        deb [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_14.x $RELEASE main
        deb-src [signed-by=/usr/share/keyrings/nodesource.gpg] https://deb.nodesource.com/node_14.x $RELEASE main
    php:
      source: 'ppa:ondrej/php'

packages:
  - f2fs-tools
  - dphys-swapfile
  - rng-tools
  - software-properties-common
  - ca-certificates
  - lsb-release
  - apt-transport-https
  - asterisk
  - apache2
  - unixodbc
  - mariadb-server
  - odbc-mariadb
  - nodejs
  - libapache2-mod-php7.4
  - php7.4
  - php-pear
  - php7.4-cgi
  - php7.4-common
  - php7.4-curl
  - php7.4-cli
  - php7.4-mbstring
  - php7.4-gd
  - php7.4-mysql
  - php7.4-bcmath
  - php7.4-zip
  - php7.4-xml
  - php7.4-imap
  - php7.4-json
  - php7.4-snmp
  - php7.4-mbstring
  - php7.4-intl
  - build-essential
  - pkgconf
  - libicu-dev
  - mpg321

write_files:
  - path: /lib/systemd/system-preset/asterisk.preset
    content: disable asterisk.service
  - path: /lib/systemd/system-preset/apache2.preset
    content: disable apache2.service
  - path: /lib/systemd/system-preset/dphys-swapfile.preset
    content: disable dphys-swapfile.service
  - path: /lib/systemd/system-preset/apache-htcacheclean.preset
    content: disable apache-htcacheclean.service
  - path: /etc/dphys-swapfile
    content: CONF_SWAPFACTOR=1
  - path: /etc/sysctl.d/15-swap.conf
    content: vm.swappiness=1
  - path: /usr/share/keyrings/nodesource.gpg
    permissions: '0644'
    owner: 'root:root'
    content: !!binary |
      mQINBFObJLYBEADkFW8HMjsoYRJQ4nCYC/6Eh0yLWHWfCh+/9ZSIj4w/pOe2V6V+W6DHY3kK3a+2
      bxrax9EqKe7uxkSKf95gfns+I9+R+RJfRpb1qvljURr54y35IZgsfMG22Np+TmM2RLgdFCZa18h0
      +RbH9i0b+ZrB9XPZmLb/h9ou7SowGqQ3wwOtT3Vyqmif0A2GCcjFTqWW6TXaY8eZJ9BCEqW3k/0C
      jw7K/mSy/utxYiUIvZNKgaG/P8U789QyvxeRxAf93YFAVzMXhoKxu12IuH4VnSwAfb8gQyxKRyiG
      OUwk0YoBPpqRnMmDDl7SdmY3oQHEJzBelTMjTM8AjbB9mWoPBX5G8t4u47/FZ6PgdfmRg9hsKXhk
      LJc7C1btblOHNgDx19fzASWX+xOjZiKpP6MkEEzq1bilUFul6RDtxkTWsTa5TGixgCB/G2fK8I9J
      L/yQhDc6OGY9mjPOxMb5PgUlT8ox3v8wt25erWj9z30QoEBwfSg4tzLcJq6N/iepQemNfo6Is+TG
      +JzI6vhXjlsBm/Xmz0ZiFPPObAH/vGCY5I6886vXQ7ftqWHYHT8jz/R4tigMGC+tvZ/kcmYBsLCC
      I5uSEP6JJRQQhHrCvOX0UaytItfsQfLmEYRd2F72o1yGh3yvWWfDIBXRmaBuIGXGpajC0JyBGSOW
      b9UxMNZY/2LJEwARAQABtB9Ob2RlU291cmNlIDxncGdAbm9kZXNvdXJjZS5jb20+iQI4BBMBAgAi
      BQJTmyS2AhsDBgsJCAcDAgYVCAIJCgsEFgIDAQIeAQIXgAAKCRAWVaCraFdigHTmD/9OKhUyjJ+h
      8gMRg6ri5EQxOExccSRU0i7UHktecSs0DVC4lZG9AOzBe+Q36cym5Z1di6JQkHl69q3zBdV3KTW+
      H1pdmnZlebYGz8paG9iQ/wS9gpnSeEyx0Enyi167Bzm0O4A1GK0prkLnz/yROHHEfHjsTgMvFwAn
      f9uaxwWgE1d1RitIWgJpAnp1DZ5O0uVlsPPmXAhuBJ32mU8S5BezPTuJJICwBlLYECGb1Y65Cil4
      OALU7T7sbUqfLCuaRKxuPtcUVnJ6/qiyPygvKZWhV6Od0Yxlyed1kftMJyYoL8kPHfeHJ+vIyt0s
      7cropfiwXoka1iJB5nKyt/eqMnPQ9aRpqkm9ABS/r7AauMA/9RALudQRHBdWIzfIg0Mlqb52yyTI
      IgQJHNGNX1T3z1XgZhI+Vi8SLFFSh8x9FeUZC6YJu0VXXj5iz+eZmk/nYjUt4MtcpVsVYIB7oIDI
      bImODm8ggsgrIzqxOzQVP1zsCGek5U6QFc9GYrQ+Wv3/fG8hfkDnxXLww0OGaEQxfodm8cLFZ5b8
      JaG3+Yxfe7JkNclwvRimvlAjqIiW5OK0vvfHco+YgANhQrlMnTx//IdZssaxvYytSHpPZTYw+qPE
      jbBJOLpoLrz8ZafN1uekpAqQjffIAOqW9SdIzq/kSHgl0bzWbPJPw86XzzftewjKNbkCDQRTmyS2
      ARAAxSSdQi+WpPQZfOflkx9sYJa0cWzLl2w++FQnZ1Pn5F09D/kPMNh4qOsyvXWlekaV/SseDZtV
      ziHJKm6V8TBG3flmFlC3DWQfNNFwn5+pWSB8WHG4bTA5RyYEEYfpbekMtdoWW/Ro8Kmh41nuxZDS
      uBJhDeFIp0ccnN2Lp1o6XfIeDYPegyEPSSZqrudfqLrSZhStDlJgXjeaJjW6UP6txPtYaaila9/H
      n6vF87AQ5bR2dEWB/xRJzgNwRiax7KSU0xca6xAuf+TDxCjZ5pp2JwdCjquXLTmUnbIZ9LGV54UZ
      /MeiG8yVu6pxbiGnXo4Ekbk6xgi1ewLivGmz4QRfVklV0dba3Zj0fRozfZ22qUHxCfDM7ad0eBXM
      FmHiN8hg3IUHTO+UdlX/aH3gADFAvSVDv0v8t6dGc6XE9Dr7mGEFnQMHO4zhM1HaS2Nh0TiL2tFL
      ttLbfG5oQlxCfXX9/nasj3K9qnlEg9G3+4T7lpdPmZRRe1O8cHCI5imVg6cLIiBLPO16e0fKyHIg
      YswLdrJFfaHNYM/SWJxHpX795zn+iCwyvZSlLfH9mlegOeVmj9cyhN/VOmS3QRhlYXoA2z7WZTNo
      C6iAIlyIpMTcZr+ntaGVtFOLS6fwdBqDXjmSQu66mDKwU5EkfNlbyrpzZMyFCDWEYo4AIR/18aGZ
      BYUAEQEAAYkCHwQYAQIACQUCU5sktgIbDAAKCRAWVaCraFdigIPQEACcYh8rR19wMZZ/hgYv5so6
      Y1HcJNARuzmffQKozS/rxqec0xM3wceL1AIMuGhlXFeGd0wRv/RVzeZjnTGwhN1DnCDy1I66hUTg
      ehONsfVanuP1PZKoL38EAxsMzdYgkYH6T9a4wJH/IPt+uuFTFFy3o8TKMvKaJk98+Jsp2X/QuNxh
      qpcIGaVbtQ1bn7m+k5Qe/fz+bFuUeXPivafLLlGc6KbdgMvSW9EVMO7yBy/2JE15ZJgl7lXKLQ31
      VQPAHT3an5IV2C/ie12eEqZWlnCiHV/wT+zhOkSpWdrheWfBT+achR4jDH80AS3F8jo3byQATJb3
      RoCYUCVc3u1ouhNZa5yLgYZ/iZkpk5gKjxHPudFbDdWjbGflN9k17VCf4Z9yAb9QMqHzHwIGXrb7
      ryFcuROMCLLVUp07PrTrRxnO9A/4xxECi0l/BzNxeU1gK88hEaNjIfviPR/h6Gq6KOcNKZ8rVFdw
      FpjbvwHMQBWhrqfuG3KaePvbnObKHXpfIKoAM7X2qfO+IFnLGTPyhFTcrl6vZBTMZTfZiC1XDQLu
      GUndsckuXINIU3DFWzZGr0QrqkuE/jyr7FXeUJj9B7cLo+s/TXo+RaVfi3kOc9BoxIvy/qiNGs/T
      Ky2/Ujqp/affmIMoMXSozKmga81JSwkADO1JMgUy6dApXz9kP4EE3g==

runcmd:
  - [systemctl, set-default, multi-user.target]
  - [systemctl, enable, dphys-swapfile]

updates:
  network:
    when: [boot, hotplug]
