version: 3

#
# Based on:
#
# Making tar Archives More Reproducible:
# http://www.gnu.org/software/tar/manual/html_section/Reproducibility.html
#
# http://reproducible-builds.org/docs/source-date-epoch/
#
vars:
  TAR_MTIME: --mtime=@${SOURCE_DATE_EPOCH:-0}
  TAR_MTIME0: --mtime=@0
  TAR_FLAGS: >-
    --sort=name --format=posix
    --pax-option=exthdr.name=%d/PaxHeaders/%f
    --pax-option=delete=atime,delete=ctime
    --numeric-owner --owner=0 --group=0
    --mode=go+u,go-w
    --clamp-mtime
  TAR_EXCLUDE: >-
    --exclude=cloud-init.yq
    --exclude=.task
  GZIP_FLAGS: >-
    --no-name
    --best

includes:
  hostname:
    taskfile: hostname/Taskfile.yml
    dir: hostname
    internal: true
  boot:
    taskfile: boot/Taskfile.yml
    dir: boot
    internal: true
  freepbx:
    taskfile: freepbx/Taskfile.yml
    dir: freepbx
    internal: true
  modprobe:
    taskfile: modprobe/Taskfile.yml
    dir: modprobe
    internal: true
  rpi:
    taskfile: rpi/Taskfile.yml
    dir: rpi
    internal: true
  pam:
    taskfile: pam/Taskfile.yml
    dir: pam
    internal: true
  rm-pkgs:
    taskfile: rm-pkgs/Taskfile.yml
    dir: rm-pkgs
    internal: true
  systemd-journal:
    taskfile: systemd-journal/Taskfile.yml
    dir: systemd-journal
    internal: true
  systemd-units:
    taskfile: systemd-units/Taskfile.yml
    dir: systemd-units
    internal: true
  cloud-init:
    taskfile: cloud-init/Taskfile.yml
    dir: cloud-init
    internal: true
  final-msg:
    taskfile: final-msg/Taskfile.yml
    dir: final-msg
    internal: true
  yq:
    taskfile: yq/Taskfile.yml
    dir: yq
    internal: true

tasks:
  pkg:
    desc: Create TAR package
    dir: ..
    cmds:
      - env LC_ALL=C tar -c {{.TAR_EXCLUDE}} {{.TAR_FLAGS}} {{.TAR_MTIME}} -f - tasks | gzip {{.GZIP_FLAGS}} > build/tasks.tar.gz

  cloud-init-pkg:
    internal: true
    requires:
      vars: [USER_DATA]
    dir: '..'
    env:
      TASKS_B64:
        sh: env LC_ALL=C tar -c {{.TAR_EXCLUDE}} {{.TAR_FLAGS}} {{.TAR_MTIME0}} -f - tasks | gzip {{.GZIP_FLAGS}} | base64
    cmds:
      - yq -i --from-file=tasks/cloud-init.yq {{.USER_DATA}}

  cloud-init:
    desc: clud-init configuration
    requires:
      vars: [USER_DATA, ARCHITECTURE, BUILD_DIR]
    cmds:
      - for: [modprobe, systemd-journal, systemd-units, cloud-init, freepbx, final-msg]
        task: '{{.ITEM}}:cloud-init'
        vars:
          USER_DATA: '{{.USER_DATA}}'
          ARCHITECTURE: '{{.ARCHITECTURE}}'
          BUILD_DIR: '{{.BUILD_DIR}}'
      - task: cloud-init-pkg
        vars:
          USER_DATA: '{{.USER_DATA}}'

  install:
    desc: Additional installation tasks
    requires:
      vars: [MNT_POINT, ARCHITECTURE, BUILD_DIR]
    vars:
      DPKG_ARCHITECTURE:
        sh: dpkg --print-architecture
    cmds:
      - for: [boot, systemd-journal, rpi]
        task: '{{.ITEM}}:install'
        vars:
          MNT_POINT: '{{.MNT_POINT}}'
          ARCHITECTURE: '{{default .DPKG_ARCHITECTURE .ARCHITECTURE}}'
          BUILD_DIR: '{{.BUILD_DIR}}'

  default:
    desc: Running internal tasks
    vars:
      DPKG_ARCHITECTURE:
        sh: dpkg --print-architecture 
    cmds:
      - for: [hostname, boot, systemd-journal, systemd-units, rm-pkgs, modprobe, pam, yq, freepbx, rpi]
        task: '{{.ITEM}}:default'
        vars:
          MNT_POINT: '{{.MNT_POINT}}'
          BUILD_DIR: '{{.BUILD_DIR}}'
          ARCHITECTURE: '{{default .DPKG_ARCHITECTURE .ARCHITECTURE}}'
        ignore_error: true
