version: 3

tasks:
  cloud-init:
    desc: clud-init configuration
    summary: |
      cloud-init configuration

      Required variables:

      * USER_DATA (absolute path)
    requires:
      vars: [USER_DATA]
    env:
      TASKS_B64:
        sh: tar -cz --exclude=cloud-init.yq -f - tasks | base64
    cmds:
      - yq -i --from-file=tasks/cloud-init.yq {{.USER_DATA}}
