version: 3

tasks:
  apt-get-remove:
    internal: true
    env:
      DEBIAN_FRONTEND: noninteractive
      NEEDRESTART_SUSPEND: 1
    vars:
      PKGS: >-
        rsyslog
        wpasupplicant
        multipath-tools
        snapd
        mdadm
        pi-bluetooth
        bluez
        plymouth
    cmds:
      - apt-get -y remove --purge {{.PKGS}}

  rm-var-lib-bluetooth:
    internal: true
    status:
      - test -z "$(ls -A /var/lib/bluetooth)"
    cmds:
      - rm -rf /var/lib/bluetooth/*

  rm-usr-share-plymouth:
    internal: true
    status:
      - test ! -d /usr/share/plymouth
    cmds:
      - rm -rf /usr/share/plymouth

  dir-cleanup:
    internal: true
    deps: [rm-var-lib-bluetooth, rm-usr-share-plymouth]

  rm-pkgs:
    aliases: [default]
    desc: Remove needless packages
    deps: [apt-get-remove]
    cmds:
      - task: dir-cleanup
