version: 3

tasks:
  install-fstab-uboot:
    internal: true
    requires:
      vars: [MNT_POINT]
    status:
      - test -z {{.MNT_POINT}}
    cmds:
      - sed -i -e '/^LABEL=writable/a LABEL=uboot /boot ext4 lazytime,nombcache 0 2' {{.MNT_POINT}}/etc/fstab      

  install:
    desc:  Additional instalation tasks
    status:
      - test -f {{.MNT_POINT}}/boot/firmware/headless.rpi
    cmds:
      - >-
        sed -i
        -e '/^LABEL=writable/s/errors=\([^,[:blank:]]\+\)/errors=\1,commit=15/'
        -e '/^LABEL=system-boot/s/\<\S\+\>/defaults,lazytime,tz=UTC,showexec,utf8=1,errors=remount-ro/4'
        -e '/^LABEL=system-boot/s/\<\S\+\>/2/6'
        {{.MNT_POINT}}/etc/fstab
      - sed -i -e '/^console/s/$/ audit=0/' {{.MNT_POINT}}/boot/firmware/cmdline.txt
      - task: install-fstab-uboot
        vars:
          MNT_POINT: '{{.MNT_POINT}}'

  boot:
    aliases: [default]
    desc: Modify boot options
    deps: [install]
  