version: 3

tasks:
  cloud-init:
    desc: cloud-init configuration
    requires:
      vars: [USER_DATA]
    vars:
      LOGGING_B64:
        env: yq ../../cloud-init/logging.yml | base64
    cmds:
      - yq -i --from-file=cloud-init.yq {{.USER_DATA}}
