version: 3

tasks:
  cloud-init:
    desc: cloud-init configuration
    requires:
      vars: [USER_DATA]
    vars:
      YQ_SCRIPT: >-
        .final_message = load_str("final-msg.txt")
    cmds:
      - yq -i '{{.YQ_SCRIPT}}' {{.USER_DATA}}

  final-msg:
    desc: Show final message
    aliases: [default]
    cmds:
      - echo Nothing to do

