#
# Building cloud-init
#
name: Build cloud-init

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: ./.github/actions/install-required-packages
    - name: Build cloud-init
      run: ./cloud-init.sh
    - name: Archive cloud-init
      uses: actions/upload-artifact@v3
      with:
        name: cloud-init
        path: >-
          build/cloud-init-arm*.7z
        retention-days: 1
        if-no-files-found: error
