#
# Publishing cloud-init
#
name: Publish cloud-init

permissions:
  contents: write

on:
  push:
    tags: v202*.*.*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: ./.github/actions/install-required-packages
    - name: Build cloud-init
      run: ./cloud-init.sh
    - name: Archive cloud-init
      uses: actions/upload-artifact@v3
      with:
        name: cloud-init
        path: >-
          build/cloud-init-arm*.7z
        retention-days: 1
        if-no-files-found: error

  publish:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - uses: actions/download-artifact@v3
    - name: Publish cloud-init
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        files: |
          build/cloud-init-arm*.7z
  